language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "3" # io.js
  - "2" # io.js
  - "1" # io.js
  - "0.12"
  - "0.10"
sudo: false
install:
  - npm install
script:
  # Run test script
  - npm run test
  # Run linting
  - npm run lint
after_script:
  - npm run coverage
